export type DistanceUnit = 'm' | 'ft'
export type TemperatureUnit = 'C' | 'F'
export type PressureUnit = 'bar' | 'psi'
export type WeightUnit = 'kg' | 'lbs'

export { convertDepth } from './convert-depth'
export { formattedDepth } from './formatted-depth'
export { formattedPressure } from './formatted-pressure'
export { formattedTemperature } from './formatted-temperature'
export { formattedWeight } from './formatted-weight'
export { numberToHumanSize } from './number-to-human-size'
export { durationToHumanSize } from './duration-to-human-size'
export { durationToClockFormat } from './duration-to-clock-format'
export { formatDate } from './format-date'
export { formattedName } from './formatted-name'

export * from './constants'
