name: Push to master
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@v2.1.8
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          registry-url: https://npm.pkg.github.com/
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
      - name: Tag and Release
        uses: paralenz/actions/make-release@v2.1.8
